### ISSUE TITLE
seek_bpc.py bad_crazy error

### ISSUE THREAD

**Issue by fnoop** [zougloub/libseek#7]
Hi, I'm running the instructions to calibrate as given:
```
./build/seek-test-calib
./test-calib.py
./seek_bpc.py
```
The first two go fine, but when running seek_bpc.py, I get:
```
Traceback (most recent call last):
  File "./seek_bpc.py", line 179, in <module>
    bpc.load()
  File "./seek_bpc.py", line 159, in load
    with open("bad_crazy.pickle", "r") as f:
IOError: [Errno 2] No such file or directory: 'bad_crazy.pickle'
```
If I uncomment the two lines:
```
bpc.identify()
bpc.save()
```
Then it seems to run, although by the output:
```
[001/2322] Finding recipe for bad pixel at (0,10)
...
[002/2322] Finding recipe for bad pixel at (0,26)
...
```
It's going to take hours/days to complete.

**Comment by jpschaaf** [comment]
I went down exactly this path just a few days ago.  If nothing else, a comment in the README mentioning that the lines need to be commented and what to expect would be very much appreciated.
